import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  let nameInput: string;
  const nameInputData = (e: any): void => {
    nameInput = e?.target?.value;
  };

  return (
    <>
      <Head>
        <title>Aram God Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.HomeContainer}>
        <div className={styles.ImageDiv}>
          <Image src={'/bard.png'} alt="bard emote" quality={100} width={256} height={256}/>
        </div>
        <div className={styles.HomeDiv1}>
          <p> Aram God Tracker </p>
        </div>
        <div className={styles.HomeDiv2}>
          <p> check how close u are to being a titan, a goliath, an ARAM God. </p>
        </div>
        <div className={styles.InputDiv}>
          <input className={styles.NameInput} placeholder={`Summoner Name`} onChange={ nameInputData } required={true} />
          <button className={styles.SearchButton} onClick={() => null}> Search </button>
        </div>
      </div>
    </>
  )
};
